# Generated by Django 5.1.7 on 2025-04-05 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_remove_customuser_contrasena'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='imagen',
            field=models.ImageField(default='perfiles/default.png', upload_to='perfiles/'),
        ),
    ]
