# Generated by Django 5.2 on 2025-04-08 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_customuser_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
