# Generated by Django 5.1.7 on 2025-04-28 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_contrato_monto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='id_proyecto',
        ),
        migrations.RemoveField(
            model_name='seguimientotiempo',
            name='id_tarea',
        ),
        migrations.CreateModel(
            name='objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes_objetos/')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='imagenes_objetos/')),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='imagenes_objetos/')),
                ('disponible', models.BooleanField(default=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_objetos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.objeto')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_recibidas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Proyecto',
        ),
        migrations.DeleteModel(
            name='SeguimientoTiempo',
        ),
        migrations.DeleteModel(
            name='Tarea',
        ),
    ]
