# Generated by Django 5.1.7 on 2025-04-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_remove_tarea_id_proyecto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudprestamo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('devuelto', 'Devuelto')], default='pendiente', max_length=20),
        ),
        migrations.DeleteModel(
            name='Contrato',
        ),
    ]
