# Generated by Django 5.1.7 on 2025-04-29 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_solicitudprestamo_estado_delete_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudprestamo',
            name='mensaje_contacto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
